import React from 'react';
import { FileText, Download, X, CheckCircle, ShieldAlert } from 'lucide-react';
import type { TelemetryPoint, AIInsight, SystemStats } from '../types/telemetry';

interface ReportGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  history: TelemetryPoint[];
  insights: AIInsight[];
  stats: SystemStats;
}

export const ReportGeneratorModal: React.FC<ReportGeneratorModalProps> = ({
  isOpen,
  onClose,
  history,
  insights,
  stats
}) => {
  if (!isOpen) return null;

  const pointCount = history.length;
  const avgLatency = pointCount > 0 ? (history.reduce((a, b) => a + b.latency, 0) / pointCount).toFixed(2) : '0';
  const maxLatency = pointCount > 0 ? Math.max(...history.map(p => p.latency)).toFixed(1) : '0';
  const avgThroughput = pointCount > 0 ? (history.reduce((a, b) => a + b.throughput, 0) / pointCount).toFixed(0) : '0';
  const avgCpu = pointCount > 0 ? (history.reduce((a, b) => a + b.cpuLoad, 0) / pointCount).toFixed(1) : '0';
  const maxCpu = pointCount > 0 ? Math.max(...history.map(p => p.cpuLoad)).toFixed(1) : '0';
  const avgGpu = pointCount > 0 ? (history.reduce((a, b) => a + b.gpuLoad, 0) / pointCount).toFixed(1) : '0';
  const avgError = pointCount > 0 ? (history.reduce((a, b) => a + b.errorRate, 0) / pointCount).toFixed(2) : '0';
  const avgInference = pointCount > 0 ? (history.reduce((a, b) => a + b.modelInference, 0) / pointCount).toFixed(2) : '0';

  const slaPassed = Number(avgError) <= 1.0 && Number(avgLatency) <= 100;

  // Download Markdown Report
  const handleDownloadMarkdown = () => {
    const mdContent = `# Enterprise AI Analytics System Health Report
Generated At: ${new Date().toLocaleString()}
Data Source Mode: ${stats.sourceMode} (${stats.wsStatus})

---

## 📊 Executive Summary
- **Total Points Sampled:** ${pointCount.toLocaleString()}
- **SLA Status:** ${slaPassed ? 'PASSED (99.9% Compliance)' : 'WARNING (SLA Breach Detected)'}
- **Average P99 Latency:** ${avgLatency} ms (Peak: ${maxLatency} ms)
- **Average Ingress Throughput:** ${Number(avgThroughput).toLocaleString()} req/sec
- **Average CPU Utilization:** ${avgCpu}% (Peak: ${maxCpu}%)
- **Average GPU Utilization:** ${avgGpu}%
- **Average Error Rate:** ${avgError}%
- **Average AI Inference Latency:** ${avgInference} ms
- **Anomalies Flagged (> ${stats.zThreshold}σ):** ${insights.length}

---

## 🧠 AI Diagnostic Insights & Root Cause Analysis

${insights.length === 0 ? '_No statistical anomalies (>3.0σ) flagged during this session._' : insights.map((ins, i) => `
### Anomaly #${i + 1}: ${ins.title}
- **Timestamp:** ${new Date(ins.timestamp).toLocaleTimeString()}
- **Impact Score:** ${ins.impactScore}% | **Confidence:** ${(ins.confidence * 100).toFixed(0)}%
- **Summary:** ${ins.summary}
- **Root Cause:** ${ins.rootCause}
- **Remediation Action:** ${ins.recommendedAction}
- **Tags:** ${ins.tags.join(', ')}
`).join('\n')}

---
Generated by Enterprise High-Performance AI Analytics Engine
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai_analytics_report_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Download CSV Telemetry Dump
  const handleDownloadCSV = () => {
    const headers = ['ID', 'Timestamp', 'Latency_ms', 'Throughput_req_s', 'CPU_Load_pct', 'GPU_Load_pct', 'Memory_MB', 'Error_Rate_pct', 'Model_Inference_ms', 'Z_Score', 'Is_Anomaly'];
    const rows = history.map(p => [
      p.id,
      new Date(p.timestamp).toISOString(),
      p.latency,
      p.throughput,
      p.cpuLoad,
      p.gpuLoad,
      p.memoryUsage,
      p.errorRate,
      p.modelInference,
      p.zScore || 0,
      p.isAnomaly ? 'TRUE' : 'FALSE'
    ]);

    const csvString = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csvString], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `telemetry_dump_${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(7, 10, 18, 0.85)',
      backdropFilter: 'blur(12px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 9999,
      padding: '20px'
    }}>
      <div className="glass-panel" style={{
        width: '100%',
        maxWidth: '850px',
        maxHeight: '90vh',
        overflowY: 'auto',
        padding: '24px',
        position: 'relative'
      }}>
        
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid var(--border-color)', paddingBottom: '14px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <FileText size={22} color="var(--accent-cyan)" />
            <div>
              <h2 style={{ fontSize: '1.15rem', fontWeight: '700', color: '#ffffff' }}>
                EXECUTIVE SYSTEM HEALTH & AI DIAGNOSTIC REPORT
              </h2>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                Generated At {new Date().toLocaleString()} | Source: {stats.sourceMode}
              </div>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '4px' }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Executive Summary Cards */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '12px', marginBottom: '20px' }}>
          <div style={{ background: 'rgba(15, 23, 42, 0.6)', border: '1px solid var(--border-color)', padding: '12px', borderRadius: '8px' }}>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>SLA Status</div>
            <div style={{ fontSize: '1rem', fontWeight: '700', color: slaPassed ? '#34d399' : '#fbbf24', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <CheckCircle size={16} /> {slaPassed ? 'PASS (99.9%)' : 'DEGRADED'}
            </div>
          </div>

          <div style={{ background: 'rgba(15, 23, 42, 0.6)', border: '1px solid var(--border-color)', padding: '12px', borderRadius: '8px' }}>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>Avg P99 Latency</div>
            <div className="font-mono" style={{ fontSize: '1rem', fontWeight: '700', color: '#38bdf8', marginTop: '2px' }}>
              {avgLatency} ms <span style={{ fontSize: '0.7rem', color: 'var(--text-dim)' }}>(Peak: {maxLatency}ms)</span>
            </div>
          </div>

          <div style={{ background: 'rgba(15, 23, 42, 0.6)', border: '1px solid var(--border-color)', padding: '12px', borderRadius: '8px' }}>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>Avg Throughput</div>
            <div className="font-mono" style={{ fontSize: '1rem', fontWeight: '700', color: '#34d399', marginTop: '2px' }}>
              {Number(avgThroughput).toLocaleString()} req/s
            </div>
          </div>

          <div style={{ background: 'rgba(15, 23, 42, 0.6)', border: '1px solid var(--border-color)', padding: '12px', borderRadius: '8px' }}>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>CPU / GPU Load</div>
            <div className="font-mono" style={{ fontSize: '1rem', fontWeight: '700', color: '#fbbf24', marginTop: '2px' }}>
              {avgCpu}% / {avgGpu}%
            </div>
          </div>
        </div>

        {/* Flagged AI Insights Summary */}
        <div style={{ marginBottom: '20px' }}>
          <h3 style={{ fontSize: '0.9rem', fontWeight: '700', color: '#ffffff', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <ShieldAlert size={16} color="#f43f5e" />
            Flagged Anomalies & AI Root Causes ({insights.length})
          </h3>

          {insights.length === 0 ? (
            <div style={{ background: 'rgba(15, 23, 42, 0.4)', padding: '16px', borderRadius: '6px', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
              No statistical anomalies (&gt;{stats.zThreshold}σ) detected in this sampling period. System operating within nominal baseline parameters.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '240px', overflowY: 'auto' }}>
              {insights.map(ins => (
                <div key={ins.id} style={{ background: 'rgba(7, 10, 18, 0.7)', border: '1px solid var(--border-color)', borderLeft: '3px solid var(--accent-rose)', padding: '10px 12px', borderRadius: '6px', fontSize: '0.8rem' }}>
                  <div style={{ fontWeight: '700', color: '#ffffff', marginBottom: '2px' }}>{ins.title}</div>
                  <div style={{ color: '#fbbf24', fontSize: '0.76rem', marginBottom: '4px' }}>Root Cause: {ins.rootCause}</div>
                  <div style={{ color: '#34d399', fontSize: '0.75rem' }}>Action: {ins.recommendedAction}</div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Export Options Bar */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '10px', paddingTop: '16px', borderTop: '1px solid var(--border-color)' }}>
          <button
            onClick={handleDownloadCSV}
            style={{
              padding: '8px 14px',
              borderRadius: '6px',
              border: '1px solid var(--border-color)',
              background: 'rgba(15, 23, 42, 0.6)',
              color: 'var(--text-main)',
              fontSize: '0.8rem',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            <Download size={14} /> Export CSV Dump
          </button>

          <button
            onClick={handleDownloadMarkdown}
            style={{
              padding: '8px 16px',
              borderRadius: '6px',
              border: 'none',
              background: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 100%)',
              color: '#ffffff',
              fontSize: '0.8rem',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px'
            }}
          >
            <FileText size={14} /> Download Markdown Report
          </button>
        </div>

      </div>
    </div>
  );
};
